version: '3'
services:
  db:
    image: postgres
    networks:
      - myappnet
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth:
    build: ./auth
    networks:
      - myappnet
    ports:
      - "12356:12356"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 isReady.py"]
      interval: 1s
      timeout: 5s
      retries: 5
  urlshortner:
    build: ./urlshortner
    networks:
      - myappnet
    ports:
      - "12357:12357"
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
networks:
  myappnet:
volumes:
  db_data:
