apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: honestliarisme/websysauth:latest
        env:
        - name: JWT_KEY
          value: strongkey
        - name: DBADDR
          value: http://db-service/
        - name: DBUSER
          value: postgres
        - name: DBPASSWORD
          value: password
        ports:
        - containerPort: 12356
        volumeMounts:
          - name: dbconfig
            mountPath: /webapp
            readOnly: true
      volumes:
        - name: dbconfig
          secret:
            secretName: dbconfig


