apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: honestliarisme/websysauth
        env:
        - name: JWT_KEY_FILE
          value: /run/secrets/jwtkey
        - name: DB_CONFIG_FILE
          value: /run/secrets/dbconfig
        ports:
        - containerPort: 12356

