apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: honestliarisme/websysauth:latest
        env:
        - name: JWT_KEY
          value: strongkey
        - name: DB_CONFIG_FILE
          value: /run/secrets/dbconfig
        ports:
        - containerPort: 12356
        volumeMounts:
          - name: dbconfig
            mountPath: /run/secrets/dbconfig
            readOnly: true
        volumes:
          - name: dbconfig
        secret:
          secretName: dbconfig


