apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortner-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortner
  template:
    metadata:
      labels:
        app: urlshortner
    spec:
      containers:
      - name: urlshortner-container
        image: honestliarisme/websysurl:latest
        env:
        - name: DB_CONFIG_FILE
          value: /run/secrets/conf/dbconfig
        - name: DBADDR
          value: db-service/
        - name: DBUSER
          value: postgres
        - name: DBPASSWORD
          value: password
        ports:
        - containerPort: 12357
        volumeMounts:
          - name: dbconfig
            mountPath: /run/secrets/conf
            readOnly: true
      volumes:
        - name: dbconfig
          secret:
            secretName: dbconfig
